# models.py
def obter_livros():
    return [
        {"titulo": "O Silêncio dos Inocentes", "categoria": "Suspense"},
        {"titulo": "O Iluminado", "categoria": "Suspense"},
        {"titulo": "Sherlock Holmes: Um Estudo em Vermelho", "categoria": "Suspense"},
        {"titulo": "Boneco de Neve", "categoria": "Suspense"},
        {"titulo": "A Garota no Trem", "categoria": "Suspense"},
        {"titulo": "O Chamado de Cthulhu", "categoria": "Horror"},
        {"titulo": "A Cor que Caiu do Espaço", "categoria": "Horror"},
        {"titulo": "It: A Coisa", "categoria": "Horror"},
        {"titulo": "Drácula", "categoria": "Horror"},
        {"titulo": "Frankenstein", "categoria": "Horror"},
        {"titulo": "O Exorcista", "categoria": "Horror"},
        {"titulo": "Psicose", "categoria": "Suspense"},
        {"titulo": "O Vilarejo", "categoria": "Horror"},
        {"titulo": "Orgulho e Preconceito", "categoria": "Romance"},
        {"titulo": "Como Eu Era Antes de Você", "categoria": "Romance"},
        {"titulo": "A Culpa é das Estrelas", "categoria": "Romance"},
        {"titulo": "Dom Casmurro", "categoria": "Romance"},
        {"titulo": "O Morro dos Ventos Uivantes", "categoria": "Romance"},
        {"titulo": "Jane Eyre", "categoria": "Romance"},
        {"titulo": "Amor & Gelato", "categoria": "Romance"},
        {"titulo": "É Assim que Acaba", "categoria": "Romance"},
        {"titulo": "Vermelho, Branco e Sangue Azul", "categoria": "Romance"},
        {"titulo": "Razão e Sensibilidade", "categoria": "Romance"},
        {"titulo": "Duna", "categoria": "Ficção Científica"},
        {"titulo": "Neuromancer", "categoria": "Ficção Científica"},
        {"titulo": "Fundação", "categoria": "Ficção Científica"},
        {"titulo": "Androides Sonham com Ovelhas Elétricas?", "categoria": "Ficção Científica"},
        {"titulo": "2001: Uma Odisseia no Espaço", "categoria": "Ficção Científica"},
        {"titulo": "O Guia do Mochileiro das Galáxias", "categoria": "Ficção Científica"},
        {"titulo": "O Hobbit", "categoria": "Fantasia"},
        {"titulo": "Harry Potter e a Pedra Filosofal", "categoria": "Fantasia"},
        {"titulo": "O Senhor dos Anéis: A Sociedade do Anel", "categoria": "Fantasia"},
        {"titulo": "O Nome do Vento", "categoria": "Fantasia"},
        {"titulo": "Game of Thrones", "categoria": "Fantasia"},
        {"titulo": "Crônicas de Nárnia", "categoria": "Fantasia"},
        {"titulo": "Percy Jackson e o Ladrão de Raios", "categoria": "Fantasia"},
        {"titulo": "Código Limpo", "categoria": "Tecnologia"},
        {"titulo": "Arquitetura Limpa", "categoria": "Tecnologia"},
        {"titulo": "O Programador Pragmático", "categoria": "Tecnologia"},
        {"titulo": "Design Patterns", "categoria": "Tecnologia"},
        {"titulo": "Refatoração", "categoria": "Tecnologia"},
        {"titulo": "Engenharia de Software de Moderno", "categoria": "Tecnologia"},
        {"titulo": "Entendendo Algoritmos", "categoria": "Tecnologia"},
        {"titulo": "Sapiens: Uma Breve História da Humanidade", "categoria": "História"},
        {"titulo": "O Poder do Hábito", "categoria": "Autoajuda"},
        {"titulo": "Pai Rico, Pai Pobre", "categoria": "Finanças"},
        {"titulo": "A Arte da Guerra", "categoria": "Estratégia"},
        {"titulo": "Medit Meditações", "categoria": "Filosofia"},
        {"titulo": "1984", "categoria": "Distopia"},
        {"titulo": "A Revolução dos Bichos", "categoria": "Distopia"},
        {"titulo": "Fahrenheit 451", "categoria": "Distopia"}
    ]

def filtrar_livros(lista, categoria):
    if not categoria:
        return lista
    return [l for l in lista if l["categoria"].lower() == categoria.lower()]